version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/postgres
    env_file:
      - docker.env
    restart: unless-stopped

  post:
    image: post-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - docker.env

volumes:
  postgres-data:
